@startuml
!define DARK
!include G:\WorkSpace\Java\IJCode\Design-Pattern\lib\LFT-UML.puml
' 允许各种图混合使用
allowmixing
' UML图标题
title 单例模式

/'饿汉式1'/
class Singleton1{
	..Private Field..
	- INSTANCE: Singleton1 = new Singleton1()
	--Constructor--
	- Singleton1(): void
	__Method__
	+ getInstance(): Singleton1
}
Singleton1 o--> Singleton1

/'饿汉式2'/
@enduml
