@startuml
!define DARK
!include G:\WorkSpace\Java\IJCode\Design-Pattern\lib\LFT-UML.puml
' 允许各种图混合使用
allowmixing
' UML图标题
title 模板方法模式

abstract class SoyMilk{
	..Field..
	--Constructor--
	__Method__
	+ {method} make(): void
	+ {method} select(): void
	+ {abstract}{method} addCondiments(): void
	+ {method} soak(): void
	+ {method} beat(): void
}
note left
add() 方法，添加配料，
因为不同的豆浆，配料不同，
因此做成抽象方法。
end note

class BlackBeanSoyMilk extends SoyMilk{
	..Field..
	--Constructor--
	__Method__
	+ {method} add(): void
}
class PeanutSoyMilk extends SoyMilk{
	..Field..
	--Constructor--
	__Method__
	+ {method} add(): void
}

class Client

Client .left.> BlackBeanSoyMilk
Client .right.> PeanutSoyMilk
Client .up.> SoyMilk
@enduml
