@startuml
!define DARK
!include G:\WorkSpace\Java\IJCode\Design-Pattern\lib\LFT-UML.puml

' 标题
title 状态图


[*] --> 订单生成 : 订单开始

订单生成 --> 已审核 : 电审审核

已审核--> 已审核 : 审核

已审核 --> 已发布 : 定价发布

已发布 --> 已完结 : 2小时无人接听

订单生成 --> 已完结 : 审核失败

已完结 --> [*] : 订单结束

待付款 --> 已付款 : 付款操作

已付款 --> 已完结 : 反馈[ 下款 或 拒贷 ]

已发布 --> 待付款 : 接单操作

待付款 --> 已完结 : 有人付款成功，其他接单失效




@enduml